spring.application.name=gateway


# --- Consul Discovery Configuration ---
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.prefer-ip-address=true

# --- Gateway Routing Configuration ---
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --- Actuator (Health/Monitoring) ---
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# --- Swagger / OpenAPI Configuration ---
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# --- Server Port ---
server.port=8080