spring.application.name=Gateway
server.port=8080

# Auth Service Route
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

logging.level.org.springframework.cloud.gateway=DEBUG

# Swagger/OpenAPI Aggregation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
