-- CREATE TABLE reviews (
--     id CHAR(36) PRIMARY KEY,
--     user_id BIGINT NOT NULL,
--     rater_id BIGINT NOT NULL,
--     rating FLOAT NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_user
--         FOREIGN KEY (user_id) REFERENCES users(id)
--         ON DELETE CASCADE ON UPDATE CASCADE,
--     CONSTRAINT fk_rater
--         FOREIGN KEY (rater_id) REFERENCES users(id)
--         ON DELETE CASCADE ON UPDATE CASCADE,
--     CONSTRAINT rating_range
--         CHECK (rating <= 5 AND rating >= 0)
-- );

-- CREATE UNIQUE INDEX idx_reviews_user_rater ON reviews (user_id, rater_id);
-- CREATE INDEX idx_reviews_rater_id ON reviews (rater_id);
