server:
  port: 8082

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/aiworkbench_auth_db
    username: aiworkbench_auth_usr
    password: 123456

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s

      config:
        enabled: true
        fail-fast: false
        request-connect-timeout: 2s
        request-read-timeout: 5s

  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.consul: DEBUG
    org.hibernate.SQL: DEBUG