server:
  port: 8081

spring:
  application:
    name: user-service

  main:
    web-application-type: servlet

  jackson:
    serialization:
      indent_output: true
  
  consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s

# (Optional but useful for debugging)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always