server:
  port: 8081

spring:
  application:
    name: user-service

  main:
    web-application-type: servlet

  jackson:
    serialization:
      indent_output: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,routes

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.security: DEBUG

    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | service=user-service | traceId=%X{traceId} | %logger - %msg%n"

# otel:
#   sdk:
#     disabled: false

#   service:
#     name: user-service

#   traces:
#     exporter: otlp

#   metrics:
#     exporter: none

#   logs:
#     exporter: none

#   exporter:
#     otlp:
#       endpoint: http://localhost:4317